@HostAddress = http://localhost:5042

### 1. Get all static search results

GET {{HostAddress}}/api/search
Accept: application/json

### 2. Get a single result by Id

GET {{HostAddress}}/api/search/cceca47c-2ffd-424c-9eae-84a0b7b3cf31
Accept: application/json

### 3. Post a new search result

POST {{HostAddress}}/api/search
Content-Type: application/json

{
  "fileName": "AdvancedFunctions.html",
  "fullPath": "C:\\Users\\pc\\Documents\\WebDev\\HTML\\AdvancedFunctions.html",
  "category": "WebDev/HTML",
  "fileSize": 1000,
  "priority": "High"
}

### 4. Update an existing search result by Id

PUT {{HostAddress}}/api/search/cceca47c-2ffd-424c-9eae-84a0b7b3cf31
Content-Type: application/json

{
  "id": "cceca47c-2ffd-424c-9eae-84a0b7b3cf31",
  "fileName": "General.md",
  "fullPath": "C:\\Users\\pc\\Documents\\WebDev\\CodeYou\\testsearch\\md1.md",
  "category": "WebDev/CodeYou/CSharp",
  "fileSize": 10,
  "priority": "High"
}

### 5. Delete a search result by Id

DELETE {{HostAddress}}/api/search/cceca47c-2ffd-424c-9eae-84a0b7b3cf31
